version: "3.9"

services:
  backend:
    build: .
    container_name: song-manager-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - CORS_ORIGINS=${CORS_ORIGINS}
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    command: npm run start

  mongo:
    image: mongo:7
    container_name: song-manager-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: songadmin
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
