version: "3.9"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/songs-db
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "5173:5173"   # Vite default dev port
    depends_on:
      - server

volumes:
  mongo_data:
